### ISSUE TITLE
关于代理平衡采样的问题

### ISSUE THREAD

**Issue by xmy0916** [Terminator8758/CAP-master#5]
作者您好！对于您论文中代理平衡采样的描述我理解的不是很清楚，根据论文的描述应该是一个minibatch的组成为P个代理，每个代理K张图，请问这P个代理的意思是指随机选择P个相机，每个相机下随机采样K张图么？
感谢您的回复~

**Comment by Terminator8758** [comment]
你好，一个minibatch中的P个proxy，是从所有proxy中随机采样P个所得；对每个proxy，随机采样具有该proxy标签的K张图。具体可参照训练代码中的data sampler。
