### ISSUE TITLE
关于 inter-camera损失计算的问题

### ISSUE THREAD

**Issue by mandrenday** [Terminator8758/CAP-master#7]
您好，在论文中提到计算inter-camera损失的时候，是“the K-nearest negative proxies in all cameras are taken as the hard negative proxies“，但是在代码中负样本的选择是：
sel_ind = torch.sort(temp_sims[k])[1][-self.bg_knn:]
这个是将距离排序后选择最后的self.bg_knn（代码中设置为50），是选择离得最远的50个负样本，这个和论文中提到的好像不一致，想请教一下，谢谢

**Comment by Terminator8758** [comment]
您好，torch.sort()是从小到大排序，所以选择最后的bg_knn个proxy，也即选择相似度最高的bg_knn个。谢谢
