### ISSUE TITLE
About evaluation protocal

### ISSUE THREAD

**Issue by YangJae96** [Terminator8758/CAP-master#8]
Hi,

Why did you change the traditional evaluation code to map_cmc function??

![image](https://user-images.githubusercontent.com/57695621/175315398-ee5c43fa-485f-4d6d-baa6-ef6185ec20bc.png)

**Comment by Terminator8758** [comment]
Hi, the screenshot is from reid/evaluators.py, which is an old code and not used in our code for model evaluation. 

In train_cap.py, PersonReIDMAP class is adopted for evaluation, imported from reid.utils.evaluation_metrics.retrieval.py
